Use status, kill, start, and check for dmypy
python-lsp/pylsp-mypy pull request #45
Opened 2022-10-26 20:53 UTC by tyoung-patreon

Fixes usage of dmypy so only one instance is started and they don't constantly kill eachother

2022-11-06 17:05 UTC, Richardk2n commented
Not calling status is something that changed some time ago with no particular reason as far as I can tell, so we can fix that.

Why call start after kill, would the next run not do that anyway?

Does this fix your issue?

2022-11-07 17:29 UTC, tyoung-patreon commented
This change did fix my issues, I think run works fine as well but I definitely found it more confusing when debugging and trying to identify which process was the daemon and which was being submitted to the daemon.

The bad interaction happens in the following scenario:

1. pylsp-mypy runs and starts a new dmypy command, it starts processing
2. I open a new file
3. pylsp-mypy runs and checks if dmypy is running. Instead of a successful response it just hangs
4. pylsp-mypy kills the original process and starts a new one

This continues until I stop editing files or I wait long enough for one of the dmypy tasks to fully index. It's a pretty rough experience for my project where the initial dmypy run takes several minutes, and during that time if I edit anything it starts over entirely. When I was debugging this is was helpful to have a `dmypy start` command distinct from the `dmypy run` commands so I knew which process was which, but maybe that's just personal preference.

2022-11-20 06:52 UTC, StabbarN requested changes

2022-11-20 06:52 UTC, StabbarN commented on pylsp_mypy/plugin.py
> +                subprocess.run(["dmypy", "start"], **windows_flag)
Nitpicking :)

```suggestion
                subprocess.run(["dmypy", "restart"], **windows_flag)
```
`dmypy --help` states
```
...
restart           Restart daemon (stop or kill followed by start)
...
```

2022-11-20 06:52 UTC, StabbarN commented on pylsp_mypy/plugin.py
> +                mypy_api.run_dmypy(["start"])
Nitpicking :)

```suggestion
                mypy_api.run_dmypy(["restart"])
```
`dmypy --help` states
```
...
restart           Restart daemon (stop or kill followed by start)
...
```

2022-11-20 14:00 UTC, merged

2022-12-12 07:27 UTC, delfick commented
hello, I'm wondering if you have an idea of when you'll release a new version with this change? thanks!

2022-12-12 18:28 UTC, Richardk2n commented
Now

2022-12-12 23:18 UTC, delfick commented
perfect, thanks!