Add configuration via lsp guide to README
python-lsp/pylsp-mypy pull request #78
Opened 2024-03-13 16:15 UTC by LaurenceWarne

Hi, this PR is in response to https://github.com/python-lsp/pylsp-mypy/issues/32, I've added a description for how the plugin can be configured (to the best of my understanding :slightly_smiling_face:) using lsp, and given an example similar to that given in https://github.com/python-lsp/python-lsp-ruff#configuration.

Thanks!

2024-04-24 18:04 UTC, Richardk2n commented
This is editor dependent, is it not?
I am not sure if we are responsible to provide documentation for that. In my opinion, the editor should do this.
If we do, we would need to cover a few relevant editors.
The preferred style (sadly badly documented here) is using `pyproject.toml`.
Maybe I should expand on that a little more, but I am not too keen on encouraging the use of esoteric command line editors.

2024-04-24 18:38 UTC, LaurenceWarne commented
> I am not sure if we are responsible to provide documentation for that.

Yes it will be editor depedendent, I guess I was mainly trying to address that AFAICS the README config section doesn't mention that configuration from LSP is supported at all.

> Maybe I should expand on that a little more, but I am not too keen on encouraging the use of esoteric command line editors.

I'm happy to drop the example.  How about doing something similar to https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md by sticking the configuration options in a table with the configuration key? e.g.:

| `pyproject.toml` key | LSP configuration key      | Type      | Description                                                                                                                                            | Default |
|----------------------|----------------------------|-----------|--------------------------------------------------------------------------------------------------------------------------------------------------------|---------|
| `live_mode`          | `pylsp.plugins.pylsp_mypy` | `boolean` | This writes to a tempfile every time a check is done. Turning off live_mode means you must save your changes for mypy diagnostics to update correctly. | `True`  |

etc

2024-06-12 15:51 UTC, nramirezuy commented
@LaurenceWarne do you know how to handle overrides?

```lua
 pylsp_mypy = {
    enabled = true,
    overrides = {"--python-executable", "python"},
 }
```
This ends up with this:
![image](https://github.com/python-lsp/pylsp-mypy/assets/1042865/87c86b1d-7a12-4655-9855-291f220e9ea3)

But if I configure it through `pyproject.toml` works as expected. :thinking:

2024-08-13 12:05 UTC, Richardk2n commented
@LaurenceWarne This seems sensible to me.

@nramirezuy The `true` is the placeholder for the default command line arguments, that we pass, so depending on what you insert into the `overrides` it is required.
What exactly do you mean by set from `pyprojectl.toml`?

2024-08-13 18:10 UTC, LaurenceWarne commented
> This seems sensible to me.

:+1: I've made edits to the PR

2024-08-17 13:55 UTC, Richardk2n requested changes
Maybe make the short summary in every description bold.

2024-08-17 13:55 UTC, Richardk2n commented on README.rst
> +     - Report basic progress to the LSP client. With this option, pylsp-mypy will report when mypy is running, given your editor supports LSP progress reporting. For small files this might produce an
Change 'especially in with `live_mode`' to 'especially in `live_mode`'. This typo was already present, but might as well fix it now.

2024-08-17 13:55 UTC, Richardk2n commented on README.rst
> +     - True
For TOML the `True` actually has to be lower case. It is upper case here due to historic reasons. Given that the LSP config is lower case as well (as far as I know), this is a good chance to change this.

2024-08-17 13:55 UTC, Richardk2n commented on README.rst
> +     - False
Boolean → lower case

2024-08-17 13:55 UTC, Richardk2n commented on README.rst
> +     - False
Boolean → lower case

2024-08-17 13:55 UTC, Richardk2n commented on README.rst
> +     - ``array`` of ``string`` items or ``True``
Boolean → lower case
Maybe change to '`array` of (`string` items or `true`)' for clarity.

2024-08-17 13:55 UTC, Richardk2n commented on README.rst
> +     - ``[True]``
Boolean → lower case

2024-08-17 13:55 UTC, Richardk2n commented on README.rst
> +     - False
Boolean → lower case

2024-08-17 15:54 UTC, LaurenceWarne commented
I think I've addressed everything :+1:

2024-08-17 16:00 UTC, Richardk2n commented on README.rst
> +   ** - ``dmypy``
extra *

2024-08-17 16:54 UTC, Richardk2n approved these changes

2024-08-17 16:55 UTC, merged

2024-11-15 22:57 UTC, nramirezuy commented
> @nramirezuy The `true` is the placeholder for the default command line arguments, that we pass, so depending on what you insert into the `overrides` it is required. What exactly do you mean by set from `pyprojectl.toml`?

Sorry I never came back to you, I meant setting the executable from `pyproject.toml` with [this option](https://mypy.readthedocs.io/en/stable/config_file.html#confval-python_executable).

So my configuration ended up like [this](https://github.com/nramirezuy/dotfiles/blob/main/src/tag-nvim/config/nvim/lua/plugins/lspconfig/python.lua#L50), which I think should be the default, since it works with [pyenv](https://github.com/pyenv/pyenv) and [venv](https://docs.python.org/3/library/venv.html).

**I'm not looking to start a discussion on a closed ticket**, but I'm happy to be @ in a new ticket about the subject.